# Generated by Django 5.0.1 on 2024-03-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="credit",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="debit",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="expense",
        ),
        migrations.AddField(
            model_name="expense",
            name="is_credit",
            field=models.BooleanField(default=True),
        ),
    ]
